### ISSUE TITLE
最新脚本出现找不到“getintegral”的问题

### ISSUE THREAD

**Issue by zmsnfly** [Mashiro2000/HeyTapTask#105]
> Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_BattleForHeyTap.py", line 286, in <module>
    main_handler(None,None)
  File "Mashiro2000_HeyTapTask_BattleForHeyTap.py", line 273, in main_handler
    battleForHeyTap.start()
  File "Mashiro2000_HeyTapTask_BattleForHeyTap.py", line 246, in start
    notify(self.getintegral())
AttributeError: 'BattleForHeyTap' object has no attribute 'getintegral'

**Comment by Mashiro2000** [comment]
函数名写错了，正在改
