### ISSUE TITLE
新版本青龙出现错误提示，更新新版本后通知直接内有脚本信息，跟前一个issues一样

### ISSUE THREAD

**Issue by fenglatiao** [Mashiro2000/HeyTapTask#113]
今天又更新了库，现在提示这个，ck重新抓了，三个必备数据按顺序更新了

提示内容：
任务:欢太任务中心
时间:2021-11-14 19:13:44
Traceback (most recent call last):
  File "/ql/scripts/Mashiro2000_HeyTapTask/TaskCenter.py", line 473, in <module>
    main_handler(None,None)
  File "/ql/scripts/Mashiro2000_HeyTapTask/TaskCenter.py", line 468, in main_handler
    notify(f"账号: {taskCenter.dic['user']}\n状态: 取消登录\n原因: json数据不齐全")
UnboundLocalError: local variable 'taskCenter' referenced before assignment

**Comment by Mashiro2000** [comment]
好的，我去看看

**Comment by Mashiro2000** [comment]
代码逻辑问题，我得重构

**Comment by Mashiro2000** [comment]
好了
