### ISSUE TITLE
一加加油站 flag 参数报错

### ISSUE THREAD

**Issue by Yue-xin97** [Mashiro2000/HeyTapTask#118]
## 开始执行... 2021-11-15 05:16:00

鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

任务:一加加油站
时间:2021-11-15 05:16:00
用户01637931533	登录成功
Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_OnePlusJYStation.py", line 311, in <module>
    main_handler(None,None)
  File "Mashiro2000_HeyTapTask_OnePlusJYStation.py", line 296, in main_handler
    onePlusJYStation.start()
  File "Mashiro2000_HeyTapTask_OnePlusJYStation.py", line 268, in start
    self.runBattleTask()                        # 运行任务中心
  File "Mashiro2000_HeyTapTask_OnePlusJYStation.py", line 232, in runBattleTask
    self.viewGoods(flag=1,count=6,dic=each)
TypeError: viewGoods() got an unexpected keyword argument 'flag'

**Comment by Mashiro2000** [comment]
好的，中午排错

**Comment by Mashiro2000** [comment]
已修复
