### ISSUE TITLE
Bark 在推送失败的时候报错

### ISSUE THREAD

**Issue by unsciorg** [Mashiro2000/HeyTapTask#85]
建议改一下代码
`sendNotify.py` Line 125 

````python

response = requests.get(url)

    if response.text == 200:
        print("bark 推送成功！")
    else:
        print("bark 推送失败！")
````

之前的方式在返回值不是200的情况时调用json方法会序列化失败

**Comment by Oreomeow** [comment]
好的

**Comment by Oreomeow** [comment]
我研究一下怎么改

**Comment by Oreomeow** [comment]
能否提供错误日志呢，测试之后未发现异常

**Comment by unsciorg** [comment]
````shell

http://bark.server.com:9000 "GET /xxxxxxxxxxxx//%E6%AC%A2%E5%A4%AA%E6%97%A9%E7%9D%A1%E6%89%93%E5%8D%A1/%E4%BB%BB%E5%8A%A1%3A%E6%AC%A2%E5%A4%AA%E6%97%A9%E7%9D%A1%E6%89%93%E5%8D%A1%0A%E6%97%B6%E9%97%B4%3A2021-11-03+11%3A35%3A00%%09%E7%99%BB%E5%BD%95%E6%88%90%E5%8A%9F%0A19121949110%09%E7%A7%AF%E5%88%86%E8%BF%87%E5%B0%91%EF%BC%8C%E5%8F%96%E6%B6%88%E6%8A%A5%E5%90%8D%21%0A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%0A%0A%0A%0A%E4%B8%87%E7%89%A9%E7%9A%86%E8%99%9A%EF%BC%8C%E4%B8%87%E7%89%A9%E7%9A%86%E5%85%81%E3%80%82++++----%E5%88%BA%E5%AE%A2%E4%BF%A1%E6%9D%A1 HTTP/1.1" 404 636

Traceback (most recent call last):

Exception in thread bark:

    self.run()

  File "/var/lang/python3/lib/python3.6/threading.py", line 864, in run

  File "/var/lang/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner

    self._target(*self._args, **self._kwargs)

  File "/var/user/sendNotify.py", line 125, in bark

    return complexjson.loads(self.text, **kwargs)

    response = requests.get(url).json()

  File "/var/lang/python3/lib/python3.6/site-packages/requests/models.py", line 897, in json

  File "/var/lang/python3/lib/python3.6/json/__init__.py", line 354, in loads

    return _default_decoder.decode(s)

  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```` 

bark的server地址应该是类似这样的形式 http://bark.server.com:9000/xxxxxxxxxx/推送内容
然后你在 `sendNotify.py` line 41 行是这样写的`    'BARK_PUSH': '',                    # bark IP 或设备码，例：https://api.day.app/DxHcxxxxxRxxxxxxcm/
`
如果按照例子中的配置，把最后的反斜杠配置上去后，会造成最后的GET地址中有两条反斜杠。
barkserver好像没有对多余的反斜杠做处理，导致了这个错误。

要么把bark地址的最后一个反斜杠去掉，要么更改一下返回值的处理方法。

以上，祝好

**Comment by Oreomeow** [comment]
由于 Python3.6 版本限制，可能要一个个改，后续会增加相关异常捕捉，同时对 `/` 进行处理

**Comment by unsciorg** [comment]
其实改一下判断返回200以后再进行json格式化就可以了，没必要直接进行格式化然后取status这个字段。

**Comment by Oreomeow** [comment]
已增加异常捕获和其他改进之处，测试中......
